### ISSUE TITLE
nothing happened

### ISSUE THREAD

**Issue by audio99** [opencv-java/face-detection#1]
when click start camera button nothing happened

**Comment by luigidr** [comment]
Hi,

could you provide some more details? On which operating system are you trying the application? In which IDE? With which version of OpenCV/Java?
When you click the "start" button, does the webcam of your computer start? Does the portion of interface that is above the "start" button change color (maybe it becomes black)?

Thanks!

**Comment by audio99** [comment]
OS  = Windows 10 Pro x64
IDE = Netbeans 8.1
OpenCV = 3.1.0

no,the webcam didnt start, the imageView on jafaFX didnt change at anything

**Comment by luigidr** [comment]
Thanks. Never tried with Netbeans - always used Eclipse for this project.
I'll have a look.

Just to be sure to exclude the obvious: did you set up the "_Netbeans-equivalent_" of a `User Library` named `opencv` that links both to the OpenCV jar and native libraries?

**Comment by forest-yang** [comment]
Nothing happened with my environment.
OS: MAC OS 10.12.3
IDE: Eclipse  Neon.2 Release (4.6.2)
OpenCV 3.2

PS: another case, FXHelloCV works well and can see the camera capture video.

**Comment by forest-yang** [comment]
I trace the code, file FaceDetectionController.java, this line will throw exception for thread issue:
originalFrame.setImage(imageToShow);

I copy Utils.java from [FXHelloCV](https://github.com/opencv-java/getting-started/tree/master/FXHelloCV) project, with updateImageView. 
replace with updateImageView.
it works. 
```
private void updateImageView(ImageView view, Image image)
{
	Utils.onFXThread(view.imageProperty(), image);
}
```

**Comment by luigidr** [comment]
Thanks, this repository has not been updated with the changes of [FXHelloCV](https://github.com/opencv-java/getting-started/tree/master/FXHelloCV).

I will fix the problem as soon as possible.

**Comment by petervalencic** [comment]
Hi @forest-yang forest-yang,
can you please let me know what you have modifed?

in FaceDetectionController.java there is:

```
@Override
public void run()
{
              Image imageToShow = grabFrame();
              originalFrame.setImage(imageToShow);
}
```

I get only  some random colored pixel in my camera window like this:
http://s5.postimg.org/jamvsn1qf/screenshot_1827.jpg

I'm using Netbeans with opencv 3.10 on Windows 10, Java 1.8

**Comment by luigidr** [comment]
Hi @petervalencic,

could you try if the [FXHelloCV](https://github.com/opencv-java/getting-started/tree/master/FXHelloCV) project works on your system? 

If it works, you need to copy the `Utils.java` file in your project and replace the last line you reported with the equivalent used in that project.

I hope to update this project with the new code as soon as possible.

**Comment by luigidr** [comment]
@petervalencic, I just update the repository to solve this issue.

Could you try?

**Comment by petervalencic** [comment]
I have reinstalled webcam drivers and it works fine also with old version
from github..

Will try also your new version!
thank you
