### ISSUE TITLE
lbpclassifier is not detecting

### ISSUE THREAD

**Issue by Renegade9819** [opencv-java/face-detection#2]
Everything else works fine, i followed your code properly. The Haar classifier works and detects the face. But nothing happens when i select lbpclassifier checkbox.

I use Eclipse neon 3
jdk 1.8
windows 10
opencv latest version

EDIT: Syntax Error. I am so sorry :(

**Comment by luigidr** [comment]
No problem, glad that you solved. :)

**Comment by Renegade9819** [comment]
Hello, this is a bit off topic.

I want to capture the detected images in a folder, and when the next time the application detects me, it should recognize my face(Show a name above the rectangle) by comparing the image with the image stored in the folder.

Is there a way to do this in java? any link or anything would really help
